/* tslint:disable */
/* eslint-disable */
/**
 * Test API
 * Your API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddStudent,
  Student,
  StudentsAddStudentCreate200Response,
} from '../models/index';
import {
    AddStudentFromJSON,
    AddStudentToJSON,
    StudentFromJSON,
    StudentToJSON,
    StudentsAddStudentCreate200ResponseFromJSON,
    StudentsAddStudentCreate200ResponseToJSON,
} from '../models/index';

export interface StudentsAddStudentCreateRequest {
    addStudent: AddStudent;
}

/**
 * 
 */
export class StudentsApi extends runtime.BaseAPI {

    /**
     */
    async studentsAddStudentCreateRaw(requestParameters: StudentsAddStudentCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentsAddStudentCreate200Response>> {
        if (requestParameters['addStudent'] == null) {
            throw new runtime.RequiredError(
                'addStudent',
                'Required parameter "addStudent" was null or undefined when calling studentsAddStudentCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/students/add_student/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddStudentToJSON(requestParameters['addStudent']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentsAddStudentCreate200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async studentsAddStudentCreate(requestParameters: StudentsAddStudentCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentsAddStudentCreate200Response> {
        const response = await this.studentsAddStudentCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async studentsGetStudentsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Student>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/students/get_students/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StudentFromJSON));
    }

    /**
     */
    async studentsGetStudentsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Student>> {
        const response = await this.studentsGetStudentsListRaw(initOverrides);
        return await response.value();
    }

}
