/* tslint:disable */
/* eslint-disable */
/**
 * Test API
 * Your API description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRegistration
 */
export interface UserRegistration {
    /**
     * 
     * @type {string}
     * @memberof UserRegistration
     */
    first_name: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistration
     */
    last_name: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistration
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistration
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistration
     */
    confirm_password: string;
}

/**
 * Check if a given object implements the UserRegistration interface.
 */
export function instanceOfUserRegistration(value: object): value is UserRegistration {
    if (!('first_name' in value) || value['first_name'] === undefined) return false;
    if (!('last_name' in value) || value['last_name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('confirm_password' in value) || value['confirm_password'] === undefined) return false;
    return true;
}

export function UserRegistrationFromJSON(json: any): UserRegistration {
    return UserRegistrationFromJSONTyped(json, false);
}

export function UserRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegistration {
    if (json == null) {
        return json;
    }
    return {
        
        'first_name': json['first_name'],
        'last_name': json['last_name'],
        'email': json['email'],
        'password': json['password'],
        'confirm_password': json['confirm_password'],
    };
}

export function UserRegistrationToJSON(json: any): UserRegistration {
    return UserRegistrationToJSONTyped(json, false);
}

export function UserRegistrationToJSONTyped(value?: UserRegistration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['first_name'],
        'last_name': value['last_name'],
        'email': value['email'],
        'password': value['password'],
        'confirm_password': value['confirm_password'],
    };
}

